name: Docker Image CI
on:
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Docker Build
      run: |
        docker build . -t loki1711/loki_github1.0
        docker images -a
    - name: Docker Login
      run: docker login -U ${{ secret.DOCKER_USERNAME }} -P {{ secret.DOCKER_PASSWORD }}
    - name: Docker Push
      run: docker push loki1711/loki_github1.0
